

services:
  dynus:
    container_name: dynus
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - postgres
    env_file:
      - dynus.env
    ports:
      - 8090:8080
    networks:
      - dynus

  postgres:
    container_name: postgres
    build:
      context: build/postgres
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - 5555:5432
    networks:
      - dynus

networks:
  dynus:
    name: dynus

volumes:
  postgres: